// v0.11 B6 · auto-generated by push.sh · DO NOT EDIT BY HAND.
//
// 此文件由 push.sh 在 `docker compose build` 之前用 9 个 .md 文件内容生成。
// 内容字符串嵌入 JS bundle 后无需运行时 fs，避免 Next.js standalone 文件追踪坑。

export const DOCS_CONTENT_MAP: Record<string, string> = {
  // placeholder — push.sh 会覆写本文件
  '01-quick-start': '# 快速开始\n\n> content-bundle 尚未生成，重跑 push.sh。',
  '02-modules-tour': '# 板块导览\n\n> content-bundle 尚未生成，重跑 push.sh。',
  '03-workflow': '# 推荐工作流\n\n> content-bundle 尚未生成，重跑 push.sh。',
  '04-image-best-practices': '# 图片生成最佳实践\n\n> content-bundle 尚未生成，重跑 push.sh。',
  '05-agents': '# Agents 子系统\n\n> content-bundle 尚未生成，重跑 push.sh。',
  '06-shortcuts': '# 快捷键速查\n\n> content-bundle 尚未生成，重跑 push.sh。',
  '07-faq': '# 常见问题 FAQ\n\n> content-bundle 尚未生成，重跑 push.sh。',
  '08-backup': '# 数据备份指南\n\n> content-bundle 尚未生成，重跑 push.sh。',
  '09-troubleshooting': '# 故障排查与日志\n\n> content-bundle 尚未生成，重跑 push.sh。',
};
